[package]
name = "base64-utf-detect"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
comfy-table = "7.*"
csv = "1.1.6"
evtx = "0.8.4"
encoding_rs = "0.8.35"
infer = "0.16.0"
indicatif = "0.17.9"
serde_json = "1.0.133"
regex = "1.5.5"
walkdir = "2.5.0"
